version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html:/usr/share/nginx/html"
      - "/etc/nginx/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    depends_on:
      - nginx
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/nginx/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  gogs:
    restart: always
    depends_on:
      - nginx-gen
    image: gogs/gogs
    container_name: gogs
    volumes:
      - "/srv/docker/gogs:/data"
    environment:
      - VIRTUAL_HOST=git.nlubello.eu
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=git.nlubello.eu
      - LETSENCRYPT_EMAIL=info@nlubello.eu
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: gogsmariadb_mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - /srv/docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Nlubello91
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=gogs
      - "TZ=Europe/Rome"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    volumes:
      - /sessions
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=phpmyadmin.nlubello.eu
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=phpmyadmin.nlubello.eu
      - LETSENCRYPT_EMAIL=info@nlubello.eu
    depends_on:
      - mariadb

  invoiceplane:
    restart: always
    image: sameersbn/invoiceplane:1.4.10-2
    command: app:invoiceplane
    environment:
    - DEBUG=false
    - TZ=Europe/Robe

    - DB_TYPE=mysqli
    - DB_HOST=mariadb
    - DB_USER=root
    - DB_PASS=Nlubello91
    - DB_NAME=invoiceplane_db

    - INVOICEPLANE_URL=https://fatture.nlubello.eu
    - INVOICEPLANE_BACKUPS_EXPIRY=0

    - VIRTUAL_HOST=fatture.nlubello.eu
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=9000
    - LETSENCRYPT_HOST=fatture.nlubello.eu
    - LETSENCRYPT_EMAIL=info@nlubello.eu
    depends_on:
    - mariadb
    volumes:
    - /srv/docker/invoiceplane/invoiceplane:/var/lib/invoiceplane
